In [59]:
# libraries
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torchvision import datasets, transforms
from torch.autograd import Variable
from torchvision.utils import save_image
import matplotlib.pyplot as plt
import numpy as np
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.metrics.pairwise import manhattan_distances
from sklearn.metrics import mean_squared_error
import datetime
import copy

In [4]:
def createGenerator():
    for i in range(3):
        yield (i*i + i)
    
for idx, i in enumerate(createGenerator()):
    print("idx: ", idx)
    print("value: ", i)

idx:  0
value:  0
idx:  1
value:  2
idx:  2
value:  6


In [5]:
A = np.array([0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
idx = np.random.permutation(10)
idx_sort = np.arange(10)
B = A[idx]
C = A[idx_sort]

print ("A: ", A)
print("idx: ", idx)
print("B: ", B)
print("idx_sort: ", idx_sort)
print("C: ", C)


A:  [ 0 10 20 30 40 50 60 70 80 90]
idx:  [9 8 5 7 1 0 6 3 4 2]
B:  [90 80 50 70 10  0 60 30 40 20]
idx_sort:  [0 1 2 3 4 5 6 7 8 9]
C:  [ 0 10 20 30 40 50 60 70 80 90]


In [6]:
X_2D = None
h = np.array([[1,2],[3,4],[5,6],[7,8],[9,10]])
print(h)

for i in range(5):
    if i == 0:
        X_2D = h[i]
    else:
        X_2D  = np.hstack((X_2D, h[i]))

print("New line")
print (X_2D)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
New line
[ 1  2  3  4  5  6  7  8  9 10]


In [7]:
x = np.array([1,2,3,4])
y = np.array([6,7,8,9])
vec = np.transpose(np.vstack((x, y)))
print(vec.shape)
mean = np.mean(vec, axis=0)
var = np.var (vec, axis=0)
print(mean)
print(var)
print("first vec")
print(vec)
vec = (vec - mean)
print("vec after mean")
print(vec)
vec = vec/ var
print("vec after var")
print(vec)

(4, 2)
[2.5 7.5]
[1.25 1.25]
first vec
[[1 6]
 [2 7]
 [3 8]
 [4 9]]
vec after mean
[[-1.5 -1.5]
 [-0.5 -0.5]
 [ 0.5  0.5]
 [ 1.5  1.5]]
vec after var
[[-1.2 -1.2]
 [-0.4 -0.4]
 [ 0.4  0.4]
 [ 1.2  1.2]]


In [33]:
#A = torch.tensor(np.array([[3.43, -2.9],[3.435, -2.902]]))

A = torch.tensor(np.array([[0.2, 0.8],[0.7, 0.3]]))
#A_ent = F.softmax(A, dim = 1) *  F.log_softmax(A, dim=1)

A_ent = A * torch.log(A)
ent = -1*A_ent.sum()
print("A = ", A)
print("A_ent = ", A_ent)
print("ent = ", ent)


A =  tensor([[0.2000, 0.8000],
        [0.7000, 0.3000]], dtype=torch.float64)
A_ent =  tensor([[-0.3219, -0.1785],
        [-0.2497, -0.3612]], dtype=torch.float64)
ent =  tensor(1.1113, dtype=torch.float64)


In [37]:
print(0.3*np.log(0.3))

-0.3611918412977808


In [21]:
def get_list_max_sum(list_sublists):
    max_sum = sum(list_sublists[0])
    sublist_max_sum = list_sublists[0]
    for i in range(len(list_sublists)):
        if sum(list_sublists[i]) > max_sum:
            max_sum = sum(list_sublists[i])
            sublist_max_sum = list_sublists[i]
    
    return sublist_max_sum

list_sublists = [[1,2,3],[1,5,9],[3,4,1]]
sublist_max_sum = get_list_max_sum(list_sublists)
print(sublist_max_sum)


In [23]:
a = np.log(1)
print(a)

0.0


In [30]:
# pot = np.array([-10, -3,-2,-1,1,2,3])
pot = np.array([-10, 10])
softmax = np.exp(pot)
print(softmax)
print(softmax[0]/np.sum(softmax))
print(softmax[1]/np.sum(softmax))

[4.53999298e-05 2.20264658e+04]
2.0611536181902033e-09
0.9999999979388463


In [107]:
x = np.arange(1,11).reshape(-1,1).astype(float)
y = np.arange(1,11).reshape(-1,1).astype(float)
X = np.hstack((x,y))
n_clusters = 2
print (X.shape)

print(X)
print(np.median(X, axis=0))

idx_init = np.random.permutation(X.shape[0])[:n_clusters]
cluster_centers = X[idx_init,:]
dist = manhattan_distances(X, cluster_centers)
labels = dist.argmin(axis=1)
print("cluster centers:")
print(cluster_centers)
print("dist:")
print(dist)
print("labels:")
print(labels)

(10, 2)
[[ 1.  1.]
 [ 2.  2.]
 [ 3.  3.]
 [ 4.  4.]
 [ 5.  5.]
 [ 6.  6.]
 [ 7.  7.]
 [ 8.  8.]
 [ 9.  9.]
 [10. 10.]]
[5.5 5.5]
cluster centers:
[[2. 2.]
 [7. 7.]]
dist:
[[ 2. 12.]
 [ 0. 10.]
 [ 2.  8.]
 [ 4.  6.]
 [ 6.  4.]
 [ 8.  2.]
 [10.  0.]
 [12.  2.]
 [14.  4.]
 [16.  6.]]
labels:
[0 0 0 0 1 1 1 1 1 1]


In [60]:
Y = X + 2
print(X)
print(Y)
print("")
mse = mean_squared_error(X, Y)
print(mse)

[[ 1  1]
 [ 2  2]
 [ 3  3]
 [ 4  4]
 [ 5  5]
 [ 6  6]
 [ 7  7]
 [ 8  8]
 [ 9  9]
 [10 10]]
[[ 3  3]
 [ 4  4]
 [ 5  5]
 [ 6  6]
 [ 7  7]
 [ 8  8]
 [ 9  9]
 [10 10]
 [11 11]
 [12 12]]

4.0


In [126]:
def k_medians_manhattan(X, n_clusters, cluster_centers_init = None, max_iter = 1000, tol = 1e-4, verbose = False):
    """
    Inspired to some degree by the implementation found in: https://gist.github.com/mblondel/1451300.
    Implements the algorithm k-medians by using the manhattan distance.
    Arguments:
        X: data (size: (n, d), n = number of points, d = dimension of the poitns) 
            to apply the k-medians algorithm.
        n_clusters: number of (supposed) clusters.
        cluster_centers_init: initial guess of the centers of the clusters if any.
        max_iter: maximum number of iterations of the algorithm.
        tol: tolerance of minimum variation between the previous and current iteration.
        verbose: boolean variable to use verbose mode.
        
    Outputs:
        cluster_centers: cluster centers found by the algorithm.
        labels: labels assigned according to the minimum manhattan distance
            to the cluster centers.
    """
    if cluster_centers_init is not None:
        cluster_centers = cluster_centers_init
    else:
        idx_init = np.random.permutation(X.shape[0])[:n_clusters]
        cluster_centers = X[idx_init,:]
    
    for i in range (max_iter):
        dist = manhattan_distances(X, cluster_centers)
        labels = dist.argmin(axis=1)
        cluster_centers_old = cluster_centers.copy()
        if verbose:
            print("iter = {}".format(i))
            print("cluster_centers =\n{}".format(cluster_centers))
            print("labels = {}\n".format(labels));
        for j in range(n_clusters):
            idx = np.where(labels == j)
            cluster_centers[j] = np.median(X[idx], axis=0)
        
        if mean_squared_error(cluster_centers, cluster_centers_old) < tol:
            break
    
    return cluster_centers, labels

In [127]:
cluster_centers_init = np.array ([[2.0,2.0],[7.0,7.0]])
cluster_centers, labels = k_medians_manhattan(X, n_clusters = 2, cluster_centers_init = cluster_centers_init)
print(cluster_centers)
print(labels)

[[3. 3.]
 [8. 8.]]
[0 0 0 0 0 1 1 1 1 1]


In [129]:
h = torch.tensor(np.array([[2.0, 2.0],[3.0, 3.0]]))
b = F.softmax(h, dim = 1) * h
print(b)

tensor([[1.0000, 1.0000],
        [1.5000, 1.5000]], dtype=torch.float64)


In [130]:
a = [1,2,3]
b = [4,5,6]
c = a + [b[0], b[1]]
print(c)

[1, 2, 3, 4, 5]


In [132]:
l = [1,2]
a = tuple(l)
print(a)

(1, 2)


In [137]:
np.random.randint(0, 6)

1

In [139]:
print(datetime.datetime.now().strftime("%d.%m.%Y-%H:%M:%S"))

20.10.2020-16:16:05
